{% set version = "2.0.11" %}

package:
  name: bob.io.video
  version: {{ version }}

source:
  fn: bob.io.video-{{ version }}.zip
  md5: 9c845d5880039950e79ad4fb0fb5d24c
  url: https://pypi.io/packages/source/b/bob.io.video/bob.io.video-{{ version }}.zip

build:
  entry_points:
  - bob_video_test.py = bob.io.video.script.video_test:main
  number: 0
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - pillow
  - bob.extension >2.0.4
  - bob.blitz
  - bob.core
  - bob.io.base
  - ffmpeg 2.8.*
  - boost 1.61.*
  - pkg-config

  run:
  - python
  - pillow
  - bob.extension >2.0.4
  - bob.blitz
  - bob.core
  - bob.io.base
  - ffmpeg 2.8.*
  - boost 1.61.*

test:
  commands:
  - bob_video_test.py --help
  - nosetests -sv bob.io.video

  imports:
  - bob
  - bob.io
  - bob.io.video
  - bob.io.video.script

  requires:
  - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Video I/O support for Bob

extra:
  recipe-maintainers:
  - 183amir
